from __future__ import annotations

from typing import Protocol


class UserProfilesRepository(Protocol):
    def list(self) -> list[object]: ...

    def get(self, profile_id: str) -> object | None: ...

    def create(self, profile: object) -> object: ...

    def update(self, profile_id: str, changes: dict[str, object]) -> object: ...

    def delete(self, profile_id: str) -> None: ...
