from collections.abc import Callable
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class SessionServiceBindings:
    Agent: Callable[[], Any]
    LLMMemoryClassifier: Callable[[], Any]
    _ask_agent: Callable[[], Any]
    _finish_agent_log: Callable[[], Any]
    _get_session: Callable[[], Any]
    _get_session_locked: Callable[[], Any]
    _load_user_profile_for_turn: Callable[[], Any]
    _long_term_memory_for_session: Callable[[], Any]
    _recover_orphaned_session_tasks: Callable[[], Any]
    _release_session_message_lock: Callable[[], Any]
    _retry_agent: Callable[[], Any]
    _safe_facts_events: Callable[[], Any]
    _safe_summarization_events: Callable[[], Any]
    _save_agent_state: Callable[[], Any]
    _session_failure_trace: Callable[[], Any]
    _session_initialization_error: Callable[[], Any]
    _session_message_lock: Callable[[], Any]
    _session_message_response: Callable[[], Any]
    _session_mutation_lock: Callable[[], Any]
    agent_log_store: Callable[[], Any]
    approved_memory_mutations: Callable[[], Any]
    factory: Callable[[], Any]
    generate_session_title: Callable[[], Any]
    invariants_repository: Callable[[], Any]
    mcp_turns: Callable[[], Any]
    mcp_turns_lock: Callable[[], Any]
    pending_memory: Callable[[], Any]
    pending_memory_repository: Callable[[], Any]
    profile_memory: Callable[[], Any]
    router: Callable[[], Any]
    run_in_threadpool: Callable[[], Any]
    session_lifecycle_lock: Callable[[], Any]
    session_memory_access: Callable[[], Any]
    session_message_locks: Callable[[], Any]
    sessions: Callable[[], Any]
    task_state_rules: Callable[[], Any]
    user_profiles: Callable[[], Any]
    working_memory: Callable[[], Any]
